#+TITLE: Twidget - Text Widget Library

Twidget is a text widget library in emacs. It allows you to create plain text widgets with actions.

** Installation
   
   Install the dependency: [[https://github.com/emacsorphanage/ov][ov]], and put the following code in your emacs configuration:
   
   #+BEGIN_SRC emacs-lisp
   (add-to-list 'load-path "<path/to/twidget>")
   (require 'twidget)
   #+END_SRC

** Main API
   - =with-twidget-buffer (buffer-or-name &rest body)=
   - =with-twidget-setup (&rest body)=
   - =twidget-create (twidget &rest args)=
   - =twidget-insert (&rest args)=
   - =twidget-query (bind-or-id property)=
   - =twidget-update (bind-or-id &rest properties)=
   - =twidget-multi-update (&rest twidget-properties)=
   - =twidget-delete (&rest binds-or-ids)=
   - =twidget-group (&rest body)=
   - =twidget-group-create (group &optional next-group)=
   - =twidget-group-delete (group)=
   - =twidget-page-create (&rest groups)=
   - =twidget-page-refresh (&rest groups)=

   Read [[./manual_cn.org][manual_cn.org]] for the details of each api and the examples.

** License
   Copyright © Kinney Zhang and contributors. Distributed under the [[./LICENSE][GPL v3.0]].
